### ISSUE TITLE
SB3 vec env error

### ISSUE THREAD

**Issue by justinkterry** [PettingZoo-Team/SuperSuit#78]
Learning in SB3, this code snippet fails:

```
env = pistonball_v4.parallel_env(time_penalty=-1)
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.stable_baselines3_vec_env_v0(env, n_envs, multiprocessing=False)
```

With the error:
```
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    model = exp_manager.setup_experiment()
  File "/home/justin_terry/rl-baselines3-zoo/utils/exp_manager.py", line 153, in setup_experiment
    env = self.create_envs(self.n_envs, no_log=False)
  File "/home/justin_terry/rl-baselines3-zoo/utils/exp_manager.py", line 484, in create_envs
    env = ss.stable_baselines3_vec_env_v0(env, n_envs, multiprocessing=False)
  File "/opt/conda/lib/python3.7/site-packages/supersuit/vector_constructors.py", line 31, in stable_baselines3_vec_env
    args = vec_env_args(env, num_envs)[:1]
  File "/opt/conda/lib/python3.7/site-packages/supersuit/vector_constructors.py", line 11, in vec_env_args
    return [env_fn] * num_envs, env.observation_space, env.action_space
  File "/opt/conda/lib/python3.7/site-packages/pettingzoo/utils/wrappers/order_enforcing.py", line 32, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(type(self).__name__, value))
AttributeError: 'frame_stack' object has no attribute 'observation_space'
```

While this code snippet semi-works:

```
env = pistonball_v4.parallel_env(time_penalty=-1)
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
```

Should the dedicated vec env support be removed then?

**Comment by justinkterry** [comment]
@weepingwillowben

**Comment by justinkterry** [comment]
Actually, the second code snippet doesn't work either:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/optuna/_optimize.py", line 217, in _run_trial
    value_or_values = func(trial)
  File "/home/justin_terry/rl-baselines3-zoo/utils/exp_manager.py", line 568, in objective
    **kwargs,
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/ppo/ppo.py", line 118, in __init__
    spaces.MultiBinary,
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/on_policy_algorithm.py", line 90, in __init__
    supported_action_spaces=supported_action_spaces,
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 156, in __init__
    env = self._wrap_env(env, self.verbose, monitor_wrapper)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/base_class.py", line 193, in _wrap_env
    env = Monitor(env)
  File "/opt/conda/lib/python3.7/site-packages/stable_baselines3/common/monitor.py", line 39, in __init__
    super(Monitor, self).__init__(env=env)
  File "/opt/conda/lib/python3.7/site-packages/gym/core.py", line 217, in __init__
    self.reward_range = self.env.reward_range
AttributeError: 'SBVecEnvWrapper' object has no attribute 'reward_range'
```

**Comment by justinkterry** [comment]
The "stable_baselines" vs "stable_baselines3" arguments to concat similarly don't seem to matter with SB3....?

**Comment by weepingwillowben** [comment]
The `ss.stable_baselines3_vec_env_v0` function currently only supports gym environments. Thats why the first snippet fails.

The second snippet fails because the returned environment from `pettingzoo_env_to_vec_env_v0` is not a Stable Baselines3 environment, it is a gym environment which is treated differently within stable baselines

The solution to this is to follow the example more closely:

```
env = pistonball_v4.parallel_env(time_penalty=-1)
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, n_envs, num_cpus=4, base_class='stable_baselines3')
```
